apiVersion: apps/v1
kind: Deployment
metadata:
 name: custom-dep
spec:
 selector:
   matchLabels:
     app: py-app
 replicas: 1
 template:
   metadata:
     labels:
       app: py-app
   spec:
     containers:
     - name: py-kube
   # enter the path to your image, be sure to include the correct region prefix
       image: iad.ocir.io/gse00014942/custom_py/fun:ocir
       imagePullPolicy: Always
       ports:
       - containerPort: 5000
       imagePullSecrets:
        - name: ocirsecret4
---
apiVersion: v1
kind: Service
metadata:
 name: serve-py
spec:
 type: LoadBalancer
 ports:
 - port: 80
   protocol: TCP
   targetPort: 5000
 selector:
   app: py-app